apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-app
data:
  postgresql-db-name: {{ .Values.postgresql.postgresqlDatabase | quote }}
  postgresql-host: {{ .Values.postgresql.postgresqlHost | quote }}
  postgresql-username: {{ .Values.postgresql.postgresqlUsername | quote }}
  postgresql-port: "{{ .Values.postgresql.postgresqlPort }}"