apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-app
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-app
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc }}