nameOverride: ""
fullnameOverride: ""

app:
  replicaCount: 1
  image:
    repository: windforlife
    pullPolicy: IfNotPresent
    tag: "1.0.0"
  imagePullSecrets: []
  # We want to inject env vars in our container app.
  env:
    MY_NEEDED_ENV_VAR: 14
    MY_OTHER_NEEDED_ENV_VAR: "development"
    POSTGRESQL_HOST: "localhost"
    POSTGRESQL_USER: "postgres"
    POSTGRESSQL_PORT: 5432
    POSTGRESQL_PASSWORD: "postgressecret"
    POSTGRESQL_DATABASE: "mydatabase"
  serviceAccount:
    create: true
    name: ""
  service:
    type: LoadBalncer
    port: 80
    targetPort: 80
  ingress:
    enabled: false
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  # Increase resource limits and request to prevent OOM issues  
  resources:
    limits:
      cpu: "250m"   
      memory: "512Mi"
    requests:
      cpu: "125m"
      memory: "256Mi"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

postgresql:
  useExternal: false
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgressecret"
  postgresqlDatabase: "mydatabase"
  postgresqlHost: "localhost"
  postgresqlPort: 5432

redis:
  password: "mysupersecretredispassword"
